# DEFAULTS:
REPEAT: 1
GLOBAL_REPEAT: 2
name: skip # with name=skip, training will be skipped
precision: 16 # 16 for mixed precision or anything else for default 32 bit
queue: null # specify path for queue file, if null keeps queue in memory

directory: temp/21.04.17_tests

# REP is a value from [0, REPEAT-1] interval
# RND_IDX is automatically assigned in `run.py`
full_path: eval f"{directory}/{name}/{RND_IDX}/{REP}"
checkpoint: eval f"{directory}/{name}/{RND_IDX}/{REP}.h5"
yaml_logdir: eval f"{directory}/{name}/{RND_IDX}/{REP}.yaml"

dataset: cifar10 # mnist|cifar10 available
num_iterations: 200
steps_per_epoch: 2000

optimizer: tf.optimizers.SGD
optimizer_config:
    learning_rate: tf.optimizers.schedules.PiecewiseConstantDecay([32000, 48000, 64000], [0.1, 0.02, 0.004, 0.0008])
    momentum: 0.9
    nesterov: True

pruning: none # none|random|l1|snip|grasp + shuffle weight|layer|mask
pruning_config:
    structure: false # true for classic structural pruning | int N for enforcing N groups
    sparsity: 0

model: lenet
model_config:
    input_shape: [32, 32, 3]
    layer_sizes: [400, 400, 400]
    n_classes: 10
    l2_reg: 1e-4

# EXPERIMENTS:
---
name: WRN16_8_full_with_2.5_preactivateF
num_iterations: 80000

model: WRN
model_config:
    N: 16
    K: 8
    input_shape: [32, 32, 3]
    n_classes: 10
    l2_reg: 2.5e-4
    preactivate_blocks: false
---
name: WRN16_8_full_with_2.5_preactivateT
num_iterations: 80000

model: WRN
model_config:
    N: 16
    K: 8
    input_shape: [32, 32, 3]
    n_classes: 10
    l2_reg: 2.5e-4
    preactivate_blocks: true
