# DEFAULT CONFIG:

REPEAT: 1  # e.g. 1, 1, 2, 2
GLOBAL_REPEAT: 1  # e.g. 1, 2, 1, 2
name: skip # with name=skip, training will be skipped
precision: 16 # 16 for mixed precision or anything else for default 32 bit
queue: null # specify path for queue file, if null keeps queue unaccessible in memory

directory: temp/21.04.19_tests
full_path: eval f"{directory}/{name}/{RND_IDX}/{REP}" # REP is a value from [0, REPEAT-1] interval
checkpoint: eval f"{directory}/{name}/{RND_IDX}/{REP}.h5" # RND_IDX is automatically assigned in `run.py`
yaml_logdir: eval f"{directory}/{name}/{RND_IDX}/{REP}.yaml"

num_iterations: 200
steps_per_epoch: 2000

dataset: cifar10 # mnist|cifar10 available
dataset_config:
    train_batch_size: 128
    valid_batch_size: 512
    padding: reflect

optimizer: tf.optimizers.SGD
optimizer_config:
    learning_rate: tf.optimizers.schedules.PiecewiseConstantDecay([32000, 48000, 64000], [0.1, 0.02, 0.004, 0.0008])
    momentum: 0.9
    nesterov: True

model: lenet
model_config:
    input_shape: [32, 32, 3]
    layer_sizes: [400, 400, 400]
    n_classes: 10
    l2_reg: 1e-4

pruning: none # none|random|l1|snip|grasp
pruning_config:
    structure: false # true for classic structural pruning OR int N for enforcing N groups OR false
    sparsity: 0

# EXPERIMENTS:
---
name: WRN28_2

num_iterations: 80000
dataset_config:
    train_batch_size: 128
    valid_batch_size: 512

model: WRN
model_config:
    N: 28
    K: 2
    input_shape: [32, 32, 3]
    n_classes: 10
    l2_reg: 2e-4
---
name: WRN16_8

num_iterations: 80000
dataset_config:
    train_batch_size: 128
    valid_batch_size: 512

model: WRN
model_config:
    N: 16
    K: 8
    input_shape: [32, 32, 3]
    n_classes: 10
    l2_reg: 2e-4
---
name: WRN16_10

num_iterations: 80000
dataset_config:
    train_batch_size: 128
    valid_batch_size: 512

model: WRN
model_config:
    N: 16
    K: 10
    input_shape: [32, 32, 3]
    n_classes: 10
    l2_reg: 2e-4
---
name: WRN22_8

num_iterations: 80000
dataset_config:
    train_batch_size: 128
    valid_batch_size: 512

model: WRN
model_config:
    N: 22
    K: 8
    input_shape: [32, 32, 3]
    n_classes: 10
    l2_reg: 2e-4
