# DEFAULTS:
REPEAT: 1
GLOBAL_REPEAT: 1
name: skip # with name=skip, training will be skipped
precision: 16 # 16 for mixed precision or anything else for default 32 bit
queue: null # specify path for queue file, if null keeps queue in memory

directory: temp/21.04.17_tests

# REP is a value from [0, REPEAT-1] interval
# RND_IDX is automatically assigned in `run.py`
full_path: eval f"{directory}/{name}/{RND_IDX}/{REP}"
checkpoint: eval f"{directory}/{name}/{RND_IDX}/{REP}.h5"
yaml_logdir: eval f"{directory}/{name}/{RND_IDX}/{REP}.yaml"

pruning: none # none|random|l1|snip|grasp + shuffle weight|layer|mask
pruning_config:
    structure: false # true for classic structural pruning | int N for enforcing N groups
    sparsity: 0

optimizer: tf.keras.optimizers.SGD
optimizer_config:
    learning_rate: tf.keras.optimizers.schedules.PiecewiseConstantDecay([100, 200], [0.01, 0.1, 0.2])
    momentum: 0.9
    nesterov: True

dataset: cifar10 # mnist|cifar10 available
#model: lenet
#model_config:
#    input_shape: [28, 28, 1]
#    layer_sizes: [400, 400, 400]
#    n_classes: 10
#    l2_reg: 1e-4

lr_boundaries: [6000, 12000]
lr_values: [0.1, 0.01, 0.001]
num_iterations: 200
steps_per_epoch: 20

# EXPERIMENTS:
---
name: test
model: lenet
model_config:
    input_shape: [32, 32, 3]
    layer_size: [400, 400, 400]
    n_classes: 10